import { MenuItem } from './types';

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  {
    id: 'm1',
    name: 'French Press Ethiopian',
    description: 'Single-origin Sidamo beans with elegant floral notes and a bright citrus finish. Hand-pressed to order in our custom glass vessels.',
    price: 380,
    category: 'Coffee',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDAJVkE2gZ4uBYDW0f3k8bqhg-t6HE7UufCEGVkgc5EKyzN5BYbQI-3SnPA2IxFuDrUCd3kNcTf0dAcxFI7A-Pk1wkpXeMckVg1N_eWh6t9a1NzjuVQJMciS6GvjRklB5Y9oGjSiRebDH5QHT0ZT6gRpnVrnnExfu5F5OWLhBLMA4aO_oAeQJDhk_YrCoeKUdWnJAJW4rOasdzlPeEc9zTpC9WE8XnoFOjqBMFkjbOodjNzE1lEOSwQTyEb_MrxAJEzg_Pfz-K45vc',
    tags: ['Veg', 'Single Origin'],
    isAvailable: true,
  },
  {
    id: 'm2',
    name: 'Classic Croissant',
    description: '24-hour long-fermented sourdough pastry, folded in layers with premium Normandy churned butter for the ultimate crispy flakiness.',
    price: 220,
    category: 'Pastries',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuStnwv3wEBI4caR1mcQyEyWElB01PjhTqlos4kET6lvUG7Cx8rMCZbML-y51zh_fx4RDbVGU-gp66bbxi-AgIj9phACpfcPojRhL4voXazwCoi1Tc6yb-TwsjQ_zsPQ7i697yMo9ClcMrEahObaOtk4XREj7mf-Mazqo-6tCqHeTB1KiIvuwgjgOqEu7OeOwAQlPmIIafJlUmqGKzU2KIYoVBfuwsdTGfMpu71qqilNKyYQCTmVug9GaFZ2WsgeOEByD96CjFbdyI',
    tags: ['Non-Veg', 'Normandy Butter'],
    isAvailable: true,
  },
  {
    id: 'm3',
    name: 'Sourdough Avocado',
    description: 'Freshly baked country sourdough topped with creamed Hass avocado mash, aromatic dukkah spices, and a slow-poached organic egg.',
    price: 450,
    category: 'Brunch',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA2R7ehhuUFo3FDq1juZWf3iAjuj4TKbOtPqeY_wOjK8KhYWex-O_T3UIDLwxX_U5FWjQRNeFyeT3glXvOfsaQ2qj3wp6IB8W9DdVGqb2LiuC1jBRE1hoKoCPlLaYwF2E_Cag1hMUqHzA2_KjJ7eiVqsbWm_tCETR6_SF8jaxdHiyLaERQFxhbICoCXUY6iQeYy4a7P21C-a-mSsLmW2391HeNJaTecZt3v-WXSWIACjBMwH6CLPzBRhLZIT32y9UoUb6q2rRhmv8A',
    tags: ['Veg', 'Best Seller'],
    isAvailable: true,
  },
  {
    id: 'm4',
    name: 'Gold-Flaked Caramel Macchiato',
    description: 'A decadent blend of our signature dark roast espresso and house-made salted caramel, steamed organic oat milk, topped with 24k edible gold flakes.',
    price: 640,
    category: 'Coffee',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAmdyzj5y-KeI58Gw-f-uSXrusbktNAQjVkAzI3Y0gRxXjuMCMJEcGGAuS7ROSFmiig0je-QfP-kZ97k3nkDsNP62CSr8jyl5ehz1sQ2SfJaMC2HZUFoFyC0xXOkYYUXeX-39UesNxKwIrnUvyp6kf4m1NLpvodCTdPp2OLH2BAhUOPBK_jwfzE2kCr2gO1qyUKS3C4lXOIfLbDJcuLSvyysguLHq7UOcTRTYY-_aiU5M1qdkfL6a-I72T4eEOugkZzl46E7LqpIJs',
    tags: ['Chef\'s Special', 'Veg'],
    isAvailable: true,
    isBestSeller: true,
  },
  {
    id: 'm5',
    name: 'Signature Espresso',
    description: 'Perfectly pulled double shot with rich, thick golden-brown crema. Using balanced Yirgacheffe beans loaded with notes of blueberry.',
    price: 320,
    category: 'Coffee',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDG8cmAs5Kitsuknuss3FHMkRD5_lxr7gsvHgSAiojixpcT78jyJ9PqrmAes3vrMGtaOHuPaMfntT9N5ieutWgtmFvuQpafJy1A1nBVcZ-He3QY3Z52NXzzy7ZyJJwue9JmP81AJe6EcgY2yKspr9FHLWx243xaUS67YUNC_SXarXX231-eoOcOw_hvdLN4e9-J6dBtm5EBZ9ysbMXpRsYQqOxjEHkKeMrst8IS0BT4BThXV-1ar1bwt6Rw11niLVHCn9ISvWMB6SQ',
    tags: ['Veg', 'Direct Trade'],
    isAvailable: true,
  },
  {
    id: 'm6',
    name: 'Almond Croissant',
    description: 'Double-baked croissant filled with luxury Marzipan almond paste, crusted heavily with crispy toasted slivered almonds and powdered sugar.',
    price: 280, // item 2 price was computed 560 for qty 2
    category: 'Pastries',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBBEaDgjw9SjszAKWFqstpS30rGqwHA8FZ1pXvKBYQkBGkXTgckr8FZjdE_T3Xi60Qz6iioncW0mnkbrBguEwaY0H_xMrqs2NLA5FCJ1E1Z9qZrGIjy0komJ8HhD1qmT5XGfeaZ4bk8Bbz84JIsAMgPzskiNmgmJseM0HiSK6-lYTTu9MwfDOiLtVov0WSNUj0Zz58VEi0vo5fO2qhzQGznhsBgdyMv2uFPinC6km1SCt_wK7KpcFrIHiPAD5-HBn4B6t7TCfYNLP4',
    tags: ['Veg', 'Fresh Baked'],
    isAvailable: true,
  },
  {
    id: 'm7',
    name: 'Truffle Toast',
    description: 'Sophisticated toasted sourdough brushed with fine white truffle oil, slow poached farm egg, and dusted with grated black pepper and Parmigiano.',
    price: 360,
    category: 'Brunch',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAt5GGALMgAOWcLsT_09t2R0Mf3Lpnl67wfGeJiyXRtpi3WBoNEoTvFgB-NGApe7FlufxrJc_E637bHSfO36_aC2cAWJYlr5JHg0gXDOGOaqoudd8SpO3UZQlK1FYq42mHu7Rdpak_BKFtd0yqsN3arFFlDQVJEuNZxtiprFzS10kfkwkokb3wMY22BwlSTZBCfvQQSpb1pXAlHlcxx95UKxx-cdaqY0CaANNGG-9BA5r3dqJERhPBM_EELlIEeVZWv81XxFzRQp5k',
    tags: ['Veg', 'Chef\'s Special'],
    isAvailable: true,
  },
  {
    id: 'm8',
    name: 'Salted Caramel Latte',
    description: 'Our house-crafted buttery salted caramel ribbons swirled into velvety steamed microfoam and double shots of balanced espresso.',
    price: 320,
    category: 'Coffee',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDJuNT313WYkaniqO0eCkKL_UCxsKLnqw_9YcIaweXDtFzDbySPMQ26Z4XJZ1iYD4gd6DPutLe6SLGh0jf9SzwKjaNTjNVZkK374Pu2ZEmxth7NH1W-06XeTMvmXchBT56DwOJUe_EK1z-Lc8Lth2tMpEIbDo8lSWjmrol25RriYTHRz8Um3OB9Dk19_qH_6LAy1vrL5gCSNig2cY8TG7wjSSXOxyYAvHl54-ST9RuKGvpZ9SsYalmtTJE78OS9rJFDNkt98vyWQms',
    tags: ['Artisan\'s Choice', 'Veg'],
    isAvailable: true,
    isBestSeller: true,
  },
  {
    id: 'm9',
    name: 'Velvet Latte',
    description: 'Smooth double shot espresso combined with warm silky oat milk and infused with organic Madagascan vanilla pod reduction.',
    price: 400,
    category: 'Coffee',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB2sYtzniv7u16rZfSbgHovuXdASDsD8hdBj6dy17wCBfP0EOn4XzLrRQjLoajnv1jjJZsaSZMkkQDRUCS0SfExvCZVXlEpHu9s_rspjdYgKMTwmgCcSWnUjUPoWuzUlL5j7rZqgqS5fNEAEaDtaqEY0QksceeETnP0YRzn08fxIlbssFlFZ9lfDPUR6dLcvQ-D4p40A3fEBA8FjQP7wNUjaeHAWsiYZPCoGSRkqdJgn2CbajZqBDNkxSM9vkGhChC8Wt1hl9SHsUk',
    tags: ['Veg', 'Vanilla Pods'],
    isAvailable: true,
  }
];
